Feature/#67
NHN-YesAladin/yesaladin_front pull request #77
Opened 2023-01-23 06:11 UTC by ssun4098

일단은 쿠키를 이용한 최근 본 상품 추가, 삭제 기능만 만듬

2023-01-23 06:31 UTC, SuJeong68 requested changes
조금만 더 수정해서 올려주시겠어요??

2023-01-23 06:31 UTC, SuJeong68 commented on src/main/java/shop/yesaladin/front/product/controller/QueryProductWebController.java
> +            throws JsonProcessingException {
한칸 위로... 올려주시면..ㅎㅎ

2023-01-23 06:31 UTC, SuJeong68 commented on src/main/java/shop/yesaladin/front/product/controller/QueryProductWebController.java
> +        for (Cookie cookie : request.getCookies()) {
cookie를 @CookieValue로 가져오지 않은 이유가 있을까요??

2023-01-23 06:31 UTC, SuJeong68 commented on src/main/java/shop/yesaladin/front/product/controller/WishlistController.java
> +        if (checkCookie(request)) {
여기 if는 왜 해놓으신걸까요??

2023-01-23 06:31 UTC, SuJeong68 commented on src/main/resources/application.yml
> +  gateway: https://네ㅑ.yesaladin.shop/shop/{api}
네ㅑ...이건 뭐져...?

2023-01-23 06:31 UTC, SuJeong68 commented on src/main/resources/templates/member/wishlist.html
> +        <tr th:each="recent: ${recentList}">
요부분은 미완일까요??

2023-01-23 07:03 UTC, ssun4098 commented on src/main/resources/templates/member/wishlist.html
> +        <tr th:each="recent: ${recentList}">
그 부분은 그 이미지를 어떻게 가져와야할 지 몰라서 일단 그렇게만 미완으로 해놨어요

2023-01-23 07:04 UTC, ssun4098 commented on src/main/resources/application.yml
> +  gateway: https://네ㅑ.yesaladin.shop/shop/{api}
어 뭐지 수정하겠습니다.

2023-01-23 07:05 UTC, ssun4098 commented on src/main/java/shop/yesaladin/front/product/controller/QueryProductWebController.java
> +            throws JsonProcessingException {
올릴께요

2023-01-26 02:09 UTC, nhn-academy-marco reviewed
수고하셨습니다.

2023-01-26 02:09 UTC, nhn-academy-marco commented on src/main/java/shop/yesaladin/front/product/controller/WishlistController.java
> +    public boolean checkCookie(HttpServletRequest request) {
QueryProductWebController 에서도 checkCookie method를 사용하는거 같아요.
각각 하는역할에 맞게 명확하게 method name을 지어주는게 좋을거 같아요.

2023-01-26 02:09 UTC, nhn-academy-marco commented on src/main/java/shop/yesaladin/front/product/controller/WishlistController.java
> +        return modelAndView;
model 과 modelAndView를 섞어서 사용하는거 같아요. 
하나로 맞춰주는건 어떨까요?

2023-01-26 02:09 UTC, nhn-academy-marco commented on src/main/java/shop/yesaladin/front/product/dto/WishlistResponseDto.java
> +    String registerDate;
registerDate만 default 접근제한자인 이유가 있을까요?

2023-01-26 02:09 UTC, nhn-academy-marco commented on src/main/java/shop/yesaladin/front/product/dto/WishlistResponseDto.java
> +    String registerDate;
String으로 주는 이유가 있을까요? front 에서 표현하기 위함이라면..
thymeleaf의 temporals , dates에 대해서 한께 봐보시면 좋을거 같아요.

2023-01-26 02:09 UTC, nhn-academy-marco commented on src/main/java/shop/yesaladin/front/product/controller/WishlistController.java
> +        cookie.setMaxAge(30000);
쿠키 사용시 보안에 대해서도 고려해주면 좋을거 같아요.
http only, secure cookie..

2023-01-27 05:21 UTC, closed without merging